//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace PalMed.Forms.PalMedService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebService1Soap", Namespace="http://tempuri.org/")]
    public partial class WebService1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback TestOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuardarMovimientoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuardarImagenOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuardarImagenesOperationCompleted;
        
        private System.Threading.SendOrPostCallback RetrieveImagesOperationCompleted;
        
        private System.Threading.SendOrPostCallback MarcarImagenesDescargadasOperationCompleted;
        
        private System.Threading.SendOrPostCallback RetrieveEntitiesWhereOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetNombresPacientesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetNombresInstitucionesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetImagenesDelMovimientoOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarImagenOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetIdMovimientoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetImagenesPaginatedOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFotosPaginadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFotosIdOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService1() {
            this.Url = global::PalMed.Forms.Properties.Settings.Default.PalMed_Forms_PalMedService_WebService1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event TestCompletedEventHandler TestCompleted;
        
        /// <remarks/>
        public event GuardarMovimientoCompletedEventHandler GuardarMovimientoCompleted;
        
        /// <remarks/>
        public event GuardarImagenCompletedEventHandler GuardarImagenCompleted;
        
        /// <remarks/>
        public event GuardarImagenesCompletedEventHandler GuardarImagenesCompleted;
        
        /// <remarks/>
        public event RetrieveImagesCompletedEventHandler RetrieveImagesCompleted;
        
        /// <remarks/>
        public event MarcarImagenesDescargadasCompletedEventHandler MarcarImagenesDescargadasCompleted;
        
        /// <remarks/>
        public event RetrieveEntitiesWhereCompletedEventHandler RetrieveEntitiesWhereCompleted;
        
        /// <remarks/>
        public event GetNombresPacientesCompletedEventHandler GetNombresPacientesCompleted;
        
        /// <remarks/>
        public event GetNombresInstitucionesCompletedEventHandler GetNombresInstitucionesCompleted;
        
        /// <remarks/>
        public event GetImagenesDelMovimientoCompletedEventHandler GetImagenesDelMovimientoCompleted;
        
        /// <remarks/>
        public event EliminarImagenCompletedEventHandler EliminarImagenCompleted;
        
        /// <remarks/>
        public event GetIdMovimientoCompletedEventHandler GetIdMovimientoCompleted;
        
        /// <remarks/>
        public event GetImagenesPaginatedCompletedEventHandler GetImagenesPaginatedCompleted;
        
        /// <remarks/>
        public event GetFotosPaginadoCompletedEventHandler GetFotosPaginadoCompleted;
        
        /// <remarks/>
        public event GetFotosIdCompletedEventHandler GetFotosIdCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Test", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Test(Imagen imagen, Movimiento movimiento) {
            object[] results = this.Invoke("Test", new object[] {
                        imagen,
                        movimiento});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TestAsync(Imagen imagen, Movimiento movimiento) {
            this.TestAsync(imagen, movimiento, null);
        }
        
        /// <remarks/>
        public void TestAsync(Imagen imagen, Movimiento movimiento, object userState) {
            if ((this.TestOperationCompleted == null)) {
                this.TestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestOperationCompleted);
            }
            this.InvokeAsync("Test", new object[] {
                        imagen,
                        movimiento}, this.TestOperationCompleted, userState);
        }
        
        private void OnTestOperationCompleted(object arg) {
            if ((this.TestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestCompleted(this, new TestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GuardarMovimiento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Movimiento GuardarMovimiento(Movimiento movimiento) {
            object[] results = this.Invoke("GuardarMovimiento", new object[] {
                        movimiento});
            return ((Movimiento)(results[0]));
        }
        
        /// <remarks/>
        public void GuardarMovimientoAsync(Movimiento movimiento) {
            this.GuardarMovimientoAsync(movimiento, null);
        }
        
        /// <remarks/>
        public void GuardarMovimientoAsync(Movimiento movimiento, object userState) {
            if ((this.GuardarMovimientoOperationCompleted == null)) {
                this.GuardarMovimientoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardarMovimientoOperationCompleted);
            }
            this.InvokeAsync("GuardarMovimiento", new object[] {
                        movimiento}, this.GuardarMovimientoOperationCompleted, userState);
        }
        
        private void OnGuardarMovimientoOperationCompleted(object arg) {
            if ((this.GuardarMovimientoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardarMovimientoCompleted(this, new GuardarMovimientoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GuardarImagen", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Imagen GuardarImagen(Imagen imagen) {
            object[] results = this.Invoke("GuardarImagen", new object[] {
                        imagen});
            return ((Imagen)(results[0]));
        }
        
        /// <remarks/>
        public void GuardarImagenAsync(Imagen imagen) {
            this.GuardarImagenAsync(imagen, null);
        }
        
        /// <remarks/>
        public void GuardarImagenAsync(Imagen imagen, object userState) {
            if ((this.GuardarImagenOperationCompleted == null)) {
                this.GuardarImagenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardarImagenOperationCompleted);
            }
            this.InvokeAsync("GuardarImagen", new object[] {
                        imagen}, this.GuardarImagenOperationCompleted, userState);
        }
        
        private void OnGuardarImagenOperationCompleted(object arg) {
            if ((this.GuardarImagenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardarImagenCompleted(this, new GuardarImagenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GuardarImagenes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool GuardarImagenes(Imagen imagenConFoto, Imagen[] imagenes) {
            object[] results = this.Invoke("GuardarImagenes", new object[] {
                        imagenConFoto,
                        imagenes});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GuardarImagenesAsync(Imagen imagenConFoto, Imagen[] imagenes) {
            this.GuardarImagenesAsync(imagenConFoto, imagenes, null);
        }
        
        /// <remarks/>
        public void GuardarImagenesAsync(Imagen imagenConFoto, Imagen[] imagenes, object userState) {
            if ((this.GuardarImagenesOperationCompleted == null)) {
                this.GuardarImagenesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardarImagenesOperationCompleted);
            }
            this.InvokeAsync("GuardarImagenes", new object[] {
                        imagenConFoto,
                        imagenes}, this.GuardarImagenesOperationCompleted, userState);
        }
        
        private void OnGuardarImagenesOperationCompleted(object arg) {
            if ((this.GuardarImagenesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardarImagenesCompleted(this, new GuardarImagenesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RetrieveImages", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Imagen[] RetrieveImages() {
            object[] results = this.Invoke("RetrieveImages", new object[0]);
            return ((Imagen[])(results[0]));
        }
        
        /// <remarks/>
        public void RetrieveImagesAsync() {
            this.RetrieveImagesAsync(null);
        }
        
        /// <remarks/>
        public void RetrieveImagesAsync(object userState) {
            if ((this.RetrieveImagesOperationCompleted == null)) {
                this.RetrieveImagesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetrieveImagesOperationCompleted);
            }
            this.InvokeAsync("RetrieveImages", new object[0], this.RetrieveImagesOperationCompleted, userState);
        }
        
        private void OnRetrieveImagesOperationCompleted(object arg) {
            if ((this.RetrieveImagesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetrieveImagesCompleted(this, new RetrieveImagesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MarcarImagenesDescargadas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void MarcarImagenesDescargadas(int[] imagenesIds) {
            this.Invoke("MarcarImagenesDescargadas", new object[] {
                        imagenesIds});
        }
        
        /// <remarks/>
        public void MarcarImagenesDescargadasAsync(int[] imagenesIds) {
            this.MarcarImagenesDescargadasAsync(imagenesIds, null);
        }
        
        /// <remarks/>
        public void MarcarImagenesDescargadasAsync(int[] imagenesIds, object userState) {
            if ((this.MarcarImagenesDescargadasOperationCompleted == null)) {
                this.MarcarImagenesDescargadasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMarcarImagenesDescargadasOperationCompleted);
            }
            this.InvokeAsync("MarcarImagenesDescargadas", new object[] {
                        imagenesIds}, this.MarcarImagenesDescargadasOperationCompleted, userState);
        }
        
        private void OnMarcarImagenesDescargadasOperationCompleted(object arg) {
            if ((this.MarcarImagenesDescargadasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MarcarImagenesDescargadasCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RetrieveEntitiesWhere", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] RetrieveEntitiesWhere(object dto, string where) {
            object[] results = this.Invoke("RetrieveEntitiesWhere", new object[] {
                        dto,
                        where});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void RetrieveEntitiesWhereAsync(object dto, string where) {
            this.RetrieveEntitiesWhereAsync(dto, where, null);
        }
        
        /// <remarks/>
        public void RetrieveEntitiesWhereAsync(object dto, string where, object userState) {
            if ((this.RetrieveEntitiesWhereOperationCompleted == null)) {
                this.RetrieveEntitiesWhereOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetrieveEntitiesWhereOperationCompleted);
            }
            this.InvokeAsync("RetrieveEntitiesWhere", new object[] {
                        dto,
                        where}, this.RetrieveEntitiesWhereOperationCompleted, userState);
        }
        
        private void OnRetrieveEntitiesWhereOperationCompleted(object arg) {
            if ((this.RetrieveEntitiesWhereCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetrieveEntitiesWhereCompleted(this, new RetrieveEntitiesWhereCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetNombresPacientes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetNombresPacientes() {
            object[] results = this.Invoke("GetNombresPacientes", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetNombresPacientesAsync() {
            this.GetNombresPacientesAsync(null);
        }
        
        /// <remarks/>
        public void GetNombresPacientesAsync(object userState) {
            if ((this.GetNombresPacientesOperationCompleted == null)) {
                this.GetNombresPacientesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNombresPacientesOperationCompleted);
            }
            this.InvokeAsync("GetNombresPacientes", new object[0], this.GetNombresPacientesOperationCompleted, userState);
        }
        
        private void OnGetNombresPacientesOperationCompleted(object arg) {
            if ((this.GetNombresPacientesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNombresPacientesCompleted(this, new GetNombresPacientesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetNombresInstituciones", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetNombresInstituciones() {
            object[] results = this.Invoke("GetNombresInstituciones", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetNombresInstitucionesAsync() {
            this.GetNombresInstitucionesAsync(null);
        }
        
        /// <remarks/>
        public void GetNombresInstitucionesAsync(object userState) {
            if ((this.GetNombresInstitucionesOperationCompleted == null)) {
                this.GetNombresInstitucionesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNombresInstitucionesOperationCompleted);
            }
            this.InvokeAsync("GetNombresInstituciones", new object[0], this.GetNombresInstitucionesOperationCompleted, userState);
        }
        
        private void OnGetNombresInstitucionesOperationCompleted(object arg) {
            if ((this.GetNombresInstitucionesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNombresInstitucionesCompleted(this, new GetNombresInstitucionesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetImagenesDelMovimiento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Imagen[] GetImagenesDelMovimiento(int movimientoId) {
            object[] results = this.Invoke("GetImagenesDelMovimiento", new object[] {
                        movimientoId});
            return ((Imagen[])(results[0]));
        }
        
        /// <remarks/>
        public void GetImagenesDelMovimientoAsync(int movimientoId) {
            this.GetImagenesDelMovimientoAsync(movimientoId, null);
        }
        
        /// <remarks/>
        public void GetImagenesDelMovimientoAsync(int movimientoId, object userState) {
            if ((this.GetImagenesDelMovimientoOperationCompleted == null)) {
                this.GetImagenesDelMovimientoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetImagenesDelMovimientoOperationCompleted);
            }
            this.InvokeAsync("GetImagenesDelMovimiento", new object[] {
                        movimientoId}, this.GetImagenesDelMovimientoOperationCompleted, userState);
        }
        
        private void OnGetImagenesDelMovimientoOperationCompleted(object arg) {
            if ((this.GetImagenesDelMovimientoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetImagenesDelMovimientoCompleted(this, new GetImagenesDelMovimientoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EliminarImagen", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool EliminarImagen(int imagenId) {
            object[] results = this.Invoke("EliminarImagen", new object[] {
                        imagenId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void EliminarImagenAsync(int imagenId) {
            this.EliminarImagenAsync(imagenId, null);
        }
        
        /// <remarks/>
        public void EliminarImagenAsync(int imagenId, object userState) {
            if ((this.EliminarImagenOperationCompleted == null)) {
                this.EliminarImagenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarImagenOperationCompleted);
            }
            this.InvokeAsync("EliminarImagen", new object[] {
                        imagenId}, this.EliminarImagenOperationCompleted, userState);
        }
        
        private void OnEliminarImagenOperationCompleted(object arg) {
            if ((this.EliminarImagenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarImagenCompleted(this, new EliminarImagenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetIdMovimiento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetIdMovimiento() {
            object[] results = this.Invoke("GetIdMovimiento", new object[0]);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetIdMovimientoAsync() {
            this.GetIdMovimientoAsync(null);
        }
        
        /// <remarks/>
        public void GetIdMovimientoAsync(object userState) {
            if ((this.GetIdMovimientoOperationCompleted == null)) {
                this.GetIdMovimientoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetIdMovimientoOperationCompleted);
            }
            this.InvokeAsync("GetIdMovimiento", new object[0], this.GetIdMovimientoOperationCompleted, userState);
        }
        
        private void OnGetIdMovimientoOperationCompleted(object arg) {
            if ((this.GetIdMovimientoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetIdMovimientoCompleted(this, new GetIdMovimientoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetImagenesPaginated", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Imagen[] GetImagenesPaginated(int num, string filtro) {
            object[] results = this.Invoke("GetImagenesPaginated", new object[] {
                        num,
                        filtro});
            return ((Imagen[])(results[0]));
        }
        
        /// <remarks/>
        public void GetImagenesPaginatedAsync(int num, string filtro) {
            this.GetImagenesPaginatedAsync(num, filtro, null);
        }
        
        /// <remarks/>
        public void GetImagenesPaginatedAsync(int num, string filtro, object userState) {
            if ((this.GetImagenesPaginatedOperationCompleted == null)) {
                this.GetImagenesPaginatedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetImagenesPaginatedOperationCompleted);
            }
            this.InvokeAsync("GetImagenesPaginated", new object[] {
                        num,
                        filtro}, this.GetImagenesPaginatedOperationCompleted, userState);
        }
        
        private void OnGetImagenesPaginatedOperationCompleted(object arg) {
            if ((this.GetImagenesPaginatedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetImagenesPaginatedCompleted(this, new GetImagenesPaginatedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFotosPaginado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Imagen[] GetFotosPaginado(int[] ids) {
            object[] results = this.Invoke("GetFotosPaginado", new object[] {
                        ids});
            return ((Imagen[])(results[0]));
        }
        
        /// <remarks/>
        public void GetFotosPaginadoAsync(int[] ids) {
            this.GetFotosPaginadoAsync(ids, null);
        }
        
        /// <remarks/>
        public void GetFotosPaginadoAsync(int[] ids, object userState) {
            if ((this.GetFotosPaginadoOperationCompleted == null)) {
                this.GetFotosPaginadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFotosPaginadoOperationCompleted);
            }
            this.InvokeAsync("GetFotosPaginado", new object[] {
                        ids}, this.GetFotosPaginadoOperationCompleted, userState);
        }
        
        private void OnGetFotosPaginadoOperationCompleted(object arg) {
            if ((this.GetFotosPaginadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFotosPaginadoCompleted(this, new GetFotosPaginadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFotosId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int[] GetFotosId() {
            object[] results = this.Invoke("GetFotosId", new object[0]);
            return ((int[])(results[0]));
        }
        
        /// <remarks/>
        public void GetFotosIdAsync() {
            this.GetFotosIdAsync(null);
        }
        
        /// <remarks/>
        public void GetFotosIdAsync(object userState) {
            if ((this.GetFotosIdOperationCompleted == null)) {
                this.GetFotosIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFotosIdOperationCompleted);
            }
            this.InvokeAsync("GetFotosId", new object[0], this.GetFotosIdOperationCompleted, userState);
        }
        
        private void OnGetFotosIdOperationCompleted(object arg) {
            if ((this.GetFotosIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFotosIdCompleted(this, new GetFotosIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Imagen {
        
        private int idField;
        
        private int idMovimientoField;
        
        private byte[] fotoField;
        
        private string nombreField;
        
        private string rutaField;
        
        private bool descargadoField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int IdMovimiento {
            get {
                return this.idMovimientoField;
            }
            set {
                this.idMovimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Foto {
            get {
                return this.fotoField;
            }
            set {
                this.fotoField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string Ruta {
            get {
                return this.rutaField;
            }
            set {
                this.rutaField = value;
            }
        }
        
        /// <remarks/>
        public bool Descargado {
            get {
                return this.descargadoField;
            }
            set {
                this.descargadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Movimiento {
        
        private int idField;
        
        private string nombreField;
        
        private System.DateTime fechaField;
        
        private string clienteField;
        
        private string institucionField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        public string Cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
            }
        }
        
        /// <remarks/>
        public string Institucion {
            get {
                return this.institucionField;
            }
            set {
                this.institucionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void TestCompletedEventHandler(object sender, TestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GuardarMovimientoCompletedEventHandler(object sender, GuardarMovimientoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GuardarMovimientoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GuardarMovimientoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Movimiento Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Movimiento)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GuardarImagenCompletedEventHandler(object sender, GuardarImagenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GuardarImagenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GuardarImagenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Imagen Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Imagen)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GuardarImagenesCompletedEventHandler(object sender, GuardarImagenesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GuardarImagenesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GuardarImagenesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void RetrieveImagesCompletedEventHandler(object sender, RetrieveImagesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetrieveImagesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetrieveImagesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Imagen[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Imagen[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void MarcarImagenesDescargadasCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void RetrieveEntitiesWhereCompletedEventHandler(object sender, RetrieveEntitiesWhereCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetrieveEntitiesWhereCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetrieveEntitiesWhereCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetNombresPacientesCompletedEventHandler(object sender, GetNombresPacientesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNombresPacientesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNombresPacientesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetNombresInstitucionesCompletedEventHandler(object sender, GetNombresInstitucionesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNombresInstitucionesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNombresInstitucionesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetImagenesDelMovimientoCompletedEventHandler(object sender, GetImagenesDelMovimientoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetImagenesDelMovimientoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetImagenesDelMovimientoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Imagen[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Imagen[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void EliminarImagenCompletedEventHandler(object sender, EliminarImagenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EliminarImagenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EliminarImagenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetIdMovimientoCompletedEventHandler(object sender, GetIdMovimientoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetIdMovimientoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetIdMovimientoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetImagenesPaginatedCompletedEventHandler(object sender, GetImagenesPaginatedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetImagenesPaginatedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetImagenesPaginatedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Imagen[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Imagen[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetFotosPaginadoCompletedEventHandler(object sender, GetFotosPaginadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFotosPaginadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFotosPaginadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Imagen[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Imagen[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetFotosIdCompletedEventHandler(object sender, GetFotosIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFotosIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFotosIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591